"""Merge every source track in data/raw into a single normalised dataset.

Sources differ in format (GPX / KMZ / GPKG) and in what metadata they carry, so
this flattens them to a common schema and computes lengths in metres by
projecting to UTM zone 55S, which covers Oro Province.

Writes data/processed/tracks.gpkg (layer "tracks") and a CSV summary.
"""

import re
import warnings
import zipfile
from pathlib import Path

import geopandas as gpd
import pandas as pd
import pyogrio
from shapely.geometry import LineString, MultiLineString

warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"

WGS84 = "EPSG:4326"
UTM55S = "EPSG:32755"  # WGS84 / UTM zone 55S — Oro Province, PNG
PNG_TZ = "Pacific/Port_Moresby"  # UTC+10, no DST — GPX times are UTC

# Internal names that are app defaults or device codes rather than real labels;
# fall back to the filename when we hit one of these.
PLACEHOLDER_NAMES = {"track infinity", "saved track", ""}
DEVICE_CODE = re.compile(r"^[A-Z]{3,6}\s*-\s*[A-Z0-9]{6,}$", re.I)
# "2026-02-04 09:35" style timestamps, which Locus appends or prepends to
# names. The date is already carried in its own column, so drop it from the
# label at either end.
LEADING_TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}[ T]\d{2}[:.]\d{2}(:\d{2})?\s*")
TRAILING_TIMESTAMP = re.compile(r"\s*\d{4}-\d{2}-\d{2}[ T]\d{2}[:.]\d{2}(:\d{2})?\s*$")


def clean_name(value, fallback, desc=None):
    """Resolve a usable track name, preferring real labels over app defaults.

    Locus writes timestamp-only names and device codes into the name field, so
    strip a leading timestamp and fall back to desc (when it is plain text) or
    the filename.
    """
    text = "" if value is None or (isinstance(value, float) and pd.isna(value)) else str(value).strip()
    # Names arrive with real newlines and with literal backslash-n from the
    # recording app; collapse both, plus any run of whitespace.
    text = re.sub(r"\s+", " ", text.replace("\\n", " ")).strip()

    if text and not DEVICE_CODE.match(text) and text.lower() not in PLACEHOLDER_NAMES:
        stripped = TRAILING_TIMESTAMP.sub("", LEADING_TIMESTAMP.sub("", text)).strip()
        # Trailing punctuation left behind by names written as sentences.
        stripped = stripped.rstrip(" .:-")
        if stripped and not stripped.lower().startswith("saved track"):
            return stripped

    # desc is often HTML generated by Locus; only use it when it is plain text.
    if desc is not None and not (isinstance(desc, float) and pd.isna(desc)):
        desc_text = str(desc).strip()
        if desc_text and "<" not in desc_text and len(desc_text) < 60:
            return desc_text

    return fallback


def nice_fallback(path):
    """Human-readable name derived from the filename."""
    stem = path.stem
    # Strip Locus' trailing "_2026-02-01_15-22" timestamp if present.
    parts = stem.split("_")
    while parts and (parts[-1][:1].isdigit() and ("-" in parts[-1] or parts[-1].isdigit())):
        parts.pop()
    return " ".join(parts).replace("-", " – ") if parts else stem


# Track types, ordered by the disturbance intensity they imply: a vehicle road
# carries far more than a seasonal garden path.
TYPE_ROAD = "Road"
TYPE_VILLAGE = "Village-to-village track"
TYPE_GARDEN = "Garden / survey track"
TYPE_ORDER = [TYPE_ROAD, TYPE_VILLAGE, TYPE_GARDEN]

GARDEN_PATTERNS = re.compile(r"cropping\s+cal[ae]nd[ae]r|crop\s+calendar|zone\s+six", re.I)
# "Gadzot Road" is a road; "Track from Awaru to Sigara Road" is a track that
# ends at one. The leading "Track from ..." is what separates them.
TRACK_TO_ROAD = re.compile(r"^\s*(track|path)\b.*\bto\b.*\broad\b", re.I)
ROAD_PATTERN = re.compile(r"\broad\b", re.I)


def classify(name, source_file):
    """Best-guess track type from its name, plus a confidence flag.

    Returns (type, certain). Names are the only signal available, so anything
    ambiguous is marked uncertain and listed for review rather than trusted.
    """
    text = f"{name} {source_file}"

    if GARDEN_PATTERNS.search(text):
        return TYPE_GARDEN, True

    if ROAD_PATTERN.search(name):
        # A track *to* a road is not itself a road.
        if TRACK_TO_ROAD.search(name):
            return TYPE_VILLAGE, False
        return TYPE_ROAD, True

    # Endpoints that are plainly not villages — a plot, a facility, a resource.
    if re.search(r"\bgrid\s*\d+|guest\s*house|water\s+source", name, re.I):
        return TYPE_GARDEN, False

    return TYPE_VILLAGE, True


def apply_overrides(tracks):
    """Let data/track_types.csv override the name-derived guess."""
    override_path = ROOT / "data" / "track_types.csv"
    if not override_path.exists():
        return tracks

    overrides = pd.read_csv(override_path)
    if not {"name", "type"} <= set(overrides.columns):
        print(f"  !! {override_path.name} needs 'name' and 'type' columns; ignoring")
        return tracks

    mapping = dict(zip(overrides["name"], overrides["type"]))
    hit = tracks["name"].isin(mapping)
    if hit.any():
        tracks.loc[hit, "type"] = tracks.loc[hit, "name"].map(mapping)
        tracks.loc[hit, "type_certain"] = True
        print(f"\napplied {hit.sum()} override(s) from {override_path.name}")
    unknown = set(mapping) - set(tracks["name"])
    for name in sorted(unknown):
        print(f"  !! override for unknown track name: {name!r}")
    return tracks


def kml_text(path):
    """Raw KML from a .kml or the doc.kml inside a .kmz."""
    if path.suffix.lower() == ".kmz":
        with zipfile.ZipFile(path) as z:
            names = [i.filename for i in z.infolist() if i.filename.lower().endswith(".kml")]
            if not names:
                return None
            preferred = next((n for n in names if n.lower() == "doc.kml"), names[0])
            return z.read(preferred).decode("utf8", errors="replace")
    return path.read_text(encoding="utf8", errors="replace")


def parse_kml_lines(path):
    """Rebuild line geometry from raw KML, dropping degenerate parts.

    Some recordings contain a Placemark whose MultiGeometry holds a one-point
    LineString alongside the real track. GEOS rejects the whole feature over
    that stub, which silently loses an entire track, so parse the coordinate
    blocks directly and keep only the parts with at least two points.
    """
    text = kml_text(path)
    if not text:
        return None, None

    name_match = re.search(r"<name>\s*(.*?)\s*</name>", text, re.S)
    name = name_match.group(1).strip() if name_match else None

    parts = []
    for block in re.findall(r"<coordinates>(.*?)</coordinates>", text, re.S):
        coords = []
        for token in block.split():
            bits = token.split(",")
            if len(bits) >= 2:
                try:
                    coords.append((float(bits[0]), float(bits[1])))
                except ValueError:
                    continue
        if len(coords) >= 2:
            parts.append(LineString(coords))

    if not parts:
        return None, name
    geom = parts[0] if len(parts) == 1 else MultiLineString(parts)
    return geom, name


def gpx_dates(path):
    """Earliest/latest timestamp from a GPX's track_points, if it has any."""
    try:
        pts = gpd.read_file(path, layer="track_points")
    except Exception:
        return None, None
    if pts.empty or "time" not in pts.columns:
        return None, None
    times = pd.to_datetime(pts["time"], errors="coerce", utc=True).dropna()
    if times.empty:
        return None, None
    return times.min(), times.max()


def load(path):
    """Normalise one source file into (line rows, point rows).

    Point-geometry sources are kept apart: a photo-waypoint record is not a
    track and must not be counted as one.
    """
    suffix = path.suffix.lower()
    fallback = nice_fallback(path)
    rows, point_rows = [], []

    if suffix == ".gpx":
        layers = "tracks"
        start, end = gpx_dates(path)
    else:
        layers = [row[0] for row in pyogrio.list_layers(path)]
        start = end = None

    layer_list = [layers] if isinstance(layers, str) else layers

    for layer in layer_list:
        try:
            gdf = gpd.read_file(path, layer=layer)
        except Exception as exc:
            if suffix not in (".kml", ".kmz"):
                print(f"  !! {path.name} [{layer}] unreadable: {type(exc).__name__}: {exc}")
                continue
            geom, parsed_name = parse_kml_lines(path)
            if geom is None:
                print(f"  !! {path.name} [{layer}] unreadable and unparseable: {exc}")
                continue
            print(f"  ~~ {path.name}: recovered by dropping degenerate part(s)")
            gdf = gpd.GeoDataFrame(
                [{"name": parsed_name, "geometry": geom}], geometry="geometry", crs=WGS84
            )

        if gdf.empty:
            continue
        gdf = gdf[gdf.geometry.notna()]
        if gdf.empty:
            continue

        for idx, row in gdf.reset_index(drop=True).iterrows():
            name_field = row.get("name") if "name" in gdf.columns else row.get("Name")
            name = clean_name(name_field, fallback, row.get("desc"))
            # Multi-feature sources get a segment suffix so rows stay distinct.
            if len(gdf) > 1:
                name = f"{name} (seg {idx + 1})"

            record = {
                "name": name,
                # Keep whatever the file itself claimed, so overriding a
                # device code or app default never loses provenance.
                "source_name": None if name_field is None else str(name_field).strip(),
                "source_file": path.name,
                "format": suffix.lstrip("."),
                "activity": row.get("locus_activity"),
                "start_time": start,
                "end_time": end,
                "geometry": row.geometry,
            }
            if row.geometry.geom_type in ("Point", "MultiPoint"):
                point_rows.append(record)
            else:
                rows.append(record)

    return rows, point_rows


def main():
    PROCESSED.mkdir(parents=True, exist_ok=True)
    files = sorted(p for p in RAW.iterdir() if p.suffix.lower() in {".gpkg", ".gpx", ".kmz", ".kml"})

    # An oversized KMZ is committed as an extracted .kml (scripts/slim_kmz.py).
    # Reading both would count the same track twice.
    extracted = {p.stem for p in files if p.suffix.lower() == ".kml"}
    skipped = [p for p in files if p.suffix.lower() == ".kmz" and p.stem in extracted]
    for path in skipped:
        print(f"{path.name}: skipped — superseded by {path.stem}.kml")
    files = [p for p in files if p not in skipped]

    rows, point_rows = [], []
    for path in files:
        found, points = load(path)
        note = f"{len(found)} line feature(s)"
        if points:
            note += f", {len(points)} point feature(s) held aside"
        print(f"{path.name}: {note}")
        rows.extend(found)
        point_rows.extend(points)

    tracks = gpd.GeoDataFrame(rows, geometry="geometry", crs=WGS84)

    # The same recording can be exported more than once under different
    # filenames — identical geometry, only the export timestamp differs. Keep
    # one copy so lengths do not double-count, but say what was dropped.
    tracks["_geom_key"] = tracks.geometry.to_wkb().map(hash)
    dupe_keys = tracks["_geom_key"].duplicated(keep=False)
    if dupe_keys.any():
        print("\nDUPLICATE GEOMETRY — identical tracks found in more than one file:")
        for _, grp in tracks[dupe_keys].groupby("_geom_key"):
            kept = grp.iloc[0]
            print(f"  keeping  {kept['source_file']}  ({kept['name']})")
            for _, row in grp.iloc[1:].iterrows():
                print(f"  dropping {row['source_file']}  (same geometry)")
    tracks = tracks.drop_duplicates(subset="_geom_key", keep="first").drop(columns="_geom_key")
    tracks = tracks.reset_index(drop=True)

    # Lengths need a projected CRS; degrees are meaningless as distance.
    projected = tracks.to_crs(UTM55S)
    tracks["length_km"] = (projected.length / 1000).round(2)

    def count_vertices(geom):
        parts = geom.geoms if geom.geom_type.startswith("Multi") else [geom]
        return sum(len(p.coords) for p in parts)

    tracks["vertices"] = tracks.geometry.map(count_vertices)
    # GPX timestamps are UTC; PNG is UTC+10, so an afternoon walk would
    # otherwise be reported on the previous day. Report local dates.
    local_start = pd.to_datetime(tracks["start_time"], utc=True, errors="coerce").dt.tz_convert(PNG_TZ)
    tracks["date"] = local_start.dt.strftime("%Y-%m-%d")
    tracks["start_local"] = local_start.dt.strftime("%Y-%m-%d %H:%M")

    classified = tracks.apply(lambda r: classify(r["name"], r["source_file"]), axis=1)
    tracks["type"] = [c[0] for c in classified]
    tracks["type_certain"] = [c[1] for c in classified]
    tracks = apply_overrides(tracks)

    tracks = tracks.sort_values("length_km", ascending=False).reset_index(drop=True)

    out_gpkg = PROCESSED / "tracks.gpkg"
    # Datetime columns with tz confuse some GPKG writers; keep the string form.
    tracks.drop(columns=["start_time", "end_time"]).to_file(out_gpkg, layer="tracks", driver="GPKG")

    if point_rows:
        points = gpd.GeoDataFrame(point_rows, geometry="geometry", crs=WGS84)
        points = points.drop(columns=["start_time", "end_time"])
        points.to_file(out_gpkg, layer="waypoints", driver="GPKG")
        by_source = points.groupby("source_file").size()
        print(f"\n{len(points)} point feature(s) written to layer 'waypoints' (not counted as tracks):")
        for src, count in by_source.items():
            print(f"  {src}: {count}")

    summary = tracks[
        [
            "name",
            "type",
            "type_certain",
            "source_name",
            "source_file",
            "format",
            "activity",
            "date",
            "length_km",
            "vertices",
        ]
    ]

    print("\nTrack types:")
    for kind in TYPE_ORDER:
        subset = tracks[tracks["type"] == kind]
        print(f"  {kind:26} {len(subset):>3}")
    unsure = tracks[~tracks["type_certain"]]
    if len(unsure):
        print(f"\n{len(unsure)} classification(s) to check — override in data/track_types.csv:")
        for _, row in unsure.iterrows():
            print(f"  [{row['type']}] {row['name']}")
    summary.to_csv(PROCESSED / "tracks_summary.csv", index=False)

    print(f"\n{len(tracks)} tracks, {tracks['length_km'].sum():.1f} km total")
    print(f"extent: {tracks.total_bounds}")
    print(f"\nwrote {out_gpkg}")
    print(summary.to_string(index=False))


if __name__ == "__main__":
    main()
