"""Merge every source track in data/raw into a single normalised dataset.

Sources differ in format (GPX / KMZ / GPKG) and in what metadata they carry, so
this flattens them to a common schema and computes lengths in metres by
projecting to UTM zone 55S, which covers Oro Province.

Writes data/processed/tracks.gpkg (layer "tracks") and a CSV summary.
"""

import re
import warnings
from pathlib import Path

import geopandas as gpd
import pandas as pd
import pyogrio

warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"

WGS84 = "EPSG:4326"
UTM55S = "EPSG:32755"  # WGS84 / UTM zone 55S — Oro Province, PNG
PNG_TZ = "Pacific/Port_Moresby"  # UTC+10, no DST — GPX times are UTC

# Internal names that are app defaults or device codes rather than real labels;
# fall back to the filename when we hit one of these.
PLACEHOLDER_NAMES = {"track infinity", "saved track", ""}
DEVICE_CODE = re.compile(r"^[A-Z]{3,6}\s*-\s*[A-Z0-9]{6,}$", re.I)
# Leading "2026-02-04 09:35" style timestamp, with or without trailing text.
LEADING_TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}[ T]\d{2}[:.]\d{2}(:\d{2})?\s*")


def clean_name(value, fallback, desc=None):
    """Resolve a usable track name, preferring real labels over app defaults.

    Locus writes timestamp-only names and device codes into the name field, so
    strip a leading timestamp and fall back to desc (when it is plain text) or
    the filename.
    """
    text = "" if value is None or (isinstance(value, float) and pd.isna(value)) else str(value).strip()

    if text and not DEVICE_CODE.match(text) and text.lower() not in PLACEHOLDER_NAMES:
        stripped = LEADING_TIMESTAMP.sub("", text).strip()
        if stripped and not stripped.lower().startswith("saved track"):
            return stripped

    # desc is often HTML generated by Locus; only use it when it is plain text.
    if desc is not None and not (isinstance(desc, float) and pd.isna(desc)):
        desc_text = str(desc).strip()
        if desc_text and "<" not in desc_text and len(desc_text) < 60:
            return desc_text

    return fallback


def nice_fallback(path):
    """Human-readable name derived from the filename."""
    stem = path.stem
    # Strip Locus' trailing "_2026-02-01_15-22" timestamp if present.
    parts = stem.split("_")
    while parts and (parts[-1][:1].isdigit() and ("-" in parts[-1] or parts[-1].isdigit())):
        parts.pop()
    return " ".join(parts).replace("-", " – ") if parts else stem


def gpx_dates(path):
    """Earliest/latest timestamp from a GPX's track_points, if it has any."""
    try:
        pts = gpd.read_file(path, layer="track_points")
    except Exception:
        return None, None
    if pts.empty or "time" not in pts.columns:
        return None, None
    times = pd.to_datetime(pts["time"], errors="coerce", utc=True).dropna()
    if times.empty:
        return None, None
    return times.min(), times.max()


def load(path):
    """Return a list of normalised single-row frames for one source file."""
    suffix = path.suffix.lower()
    fallback = nice_fallback(path)
    rows = []

    if suffix == ".gpx":
        layers = "tracks"
        start, end = gpx_dates(path)
    else:
        layers = [row[0] for row in pyogrio.list_layers(path)]
        start = end = None

    layer_list = [layers] if isinstance(layers, str) else layers

    for layer in layer_list:
        gdf = gpd.read_file(path, layer=layer)
        if gdf.empty:
            continue
        gdf = gdf[gdf.geometry.notna()]
        if gdf.empty:
            continue

        for idx, row in gdf.reset_index(drop=True).iterrows():
            name_field = row.get("name") if "name" in gdf.columns else row.get("Name")
            name = clean_name(name_field, fallback, row.get("desc"))
            # Multi-feature sources get a segment suffix so rows stay distinct.
            if len(gdf) > 1:
                name = f"{name} (seg {idx + 1})"

            rows.append(
                {
                    "name": name,
                    # Keep whatever the file itself claimed, so overriding a
                    # device code or app default never loses provenance.
                    "source_name": None if name_field is None else str(name_field).strip(),
                    "source_file": path.name,
                    "format": suffix.lstrip("."),
                    "activity": row.get("locus_activity"),
                    "start_time": start,
                    "end_time": end,
                    "geometry": row.geometry,
                }
            )
    return rows


def main():
    PROCESSED.mkdir(parents=True, exist_ok=True)
    files = sorted(p for p in RAW.iterdir() if p.suffix.lower() in {".gpkg", ".gpx", ".kmz", ".kml"})

    rows = []
    for path in files:
        found = load(path)
        print(f"{path.name}: {len(found)} feature(s)")
        rows.extend(found)

    tracks = gpd.GeoDataFrame(rows, geometry="geometry", crs=WGS84)

    # Lengths need a projected CRS; degrees are meaningless as distance.
    projected = tracks.to_crs(UTM55S)
    tracks["length_km"] = (projected.length / 1000).round(2)

    def count_vertices(geom):
        parts = geom.geoms if geom.geom_type.startswith("Multi") else [geom]
        return sum(len(p.coords) for p in parts)

    tracks["vertices"] = tracks.geometry.map(count_vertices)
    # GPX timestamps are UTC; PNG is UTC+10, so an afternoon walk would
    # otherwise be reported on the previous day. Report local dates.
    local_start = pd.to_datetime(tracks["start_time"], utc=True, errors="coerce").dt.tz_convert(PNG_TZ)
    tracks["date"] = local_start.dt.strftime("%Y-%m-%d")
    tracks["start_local"] = local_start.dt.strftime("%Y-%m-%d %H:%M")

    tracks = tracks.sort_values("length_km", ascending=False).reset_index(drop=True)

    out_gpkg = PROCESSED / "tracks.gpkg"
    # Datetime columns with tz confuse some GPKG writers; keep the string form.
    tracks.drop(columns=["start_time", "end_time"]).to_file(out_gpkg, layer="tracks", driver="GPKG")

    summary = tracks[
        ["name", "source_name", "source_file", "format", "activity", "date", "length_km", "vertices"]
    ]
    summary.to_csv(PROCESSED / "tracks_summary.csv", index=False)

    print(f"\n{len(tracks)} tracks, {tracks['length_km'].sum():.1f} km total")
    print(f"extent: {tracks.total_bounds}")
    print(f"\nwrote {out_gpkg}")
    print(summary.to_string(index=False))


if __name__ == "__main__":
    main()
